### ISSUE TITLE
Unhandled rejection TypeError when attempting to find a room that no longer exists

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#101]
```
[ws] CONNECTION ESTABLISHED  /api/room/c4cdd5aa-d89d-42cd-bdde-4f1de5415878 1
Grabbing room c4cdd5aa-d89d-42cd-bdde-4f1de5415878 from db
Executing (default): SELECT "id", "name", "title", "description", "createdAt", "updatedAt" FROM "Rooms" AS "Room" WHERE "Room"."name" = 'c4cdd5aa-d89d-42cd-bdde-4f1de5415878' LIMIT 1;
Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Room.findOne.then.room (/home/carson/opentogethertube/storage.js:8:4)
    at tryCatcher (/home/carson/opentogethertube/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by adapap** [comment]
Potentially fixed in #80
