### ISSUE TITLE
Videos going through an HLS proxy don't work

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#1072]
### Expected Behavior

It should work

### Steps To Reproduce

1. Try to add a video with any of these URLs

- https://server3.dlp.us.cluster.kosmi.io/dlp.m3u8?url=https://upload.wikimedia.org/wikipedia/commons/c/c0/Big_Buck_Bunny_4K.webm

### Environment

- [X] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

### Anything else?

See: https://github.com/warren-bank/HLS-Proxy

**Comment by Sysadminfromhell** [comment]
@dyc3 you got another hls-proxy to test with? If I test your link (pretty old sure) I get a 502 because I guess its not working like that anymore. If I test a normal hls file it works.

**Comment by dyc3** [comment]
You could try to set up the hls proxy i linked: https://github.com/warren-bank/HLS-Proxy

**Comment by Sysadminfromhell** [comment]
I will try to set it up but then I would need HLS Video-Links to test it. Can you provide those? Otherwise I have to ask google 😆 

EDIT:
Nevermind I guess I am to stupid to understand this HLS-Proxy Setup. I will check if there is a finished package / docker container somewhere.

**Comment by Sysadminfromhell** [comment]
@dyc3 would this one work? https://hub.docker.com/r/riftbit/hls-proxy

**Comment by Sysadminfromhell** [comment]
@dyc3 I dont know if I reproduced your error but with an internal hlsproxy I can bring ott to crash with error code 129.

```
opentogethertube           | 2025-09-20 18:17:00 infoextract warn MISSING INFO for hls:http://172.16.24.129:8888/proxy/hls/manifest.m3u8?d=https://upload.wikimedia.org/wikipedia/commons/c/c0/Big_Buck_Bunny_4K.webm&api_password=xxx: title,description,thumbnail,length,mime
opentogethertube exited with code 129
```

Before that error I tested that URL twiece. I cant get the video to play inside of OTT but in my browser it works fine.
If you want I can share steps to reproduce unfurtanatly in the url the api-password needs to be provided therefore I wont share that in public.

The console shows before it crashes a 504 Timeout.

**Comment by dyc3** [comment]
Sure, go ahead

**Comment by Sysadminfromhell** [comment]
Steps to reproduce error 129:

1. Setup or use public HLS Proxy (in my case its mediaflow-proxy(https://github.com/mhdzumair/mediaflow-proxy))
2. Use the proxy according to documentation and use HLS Proxy for any kind of stream
    http://172.16.24.129:8888/proxy/hls/manifest.m3u8?d=https://upload.wikimedia.org/wikipedia/commons/c/c0/Big_Buck_Bunny_4K.webm&api_password=xxx
3. Wait until OTT cant figure out the file and refuses to play (console says 504: timeout)
4. OTT Restart with error code 129

The issue with that is, that even with log level Debug I cant seem to find the source for that to happen.

**Comment by dyc3** [comment]
You could try running it outside of docker and use a debugger to step through it

**Comment by Sysadminfromhell** [comment]
> You could try running it outside of docker and use a debugger to step through it

Funny enough, In a dev env i cannot seem to be able to reproduce that error but now I at least can see the error instead of the error 129:

```
[0] 2025-09-20 22:20:08 infoextract error Failed to get video info for hls:http://172.16.24.129:8888/proxy/hls/manifest.m3u8?d=https://upload.wikimedia.org/wikipedia/commons/c/c0/Big_Buck_Bunny_4K.webm&api_password=xxx: Cannot read properties of undefined (reading 'title') TypeError: Cannot read properties of undefined (reading 'title')
[0]     at HlsVideoAdapter.handleM3u8 (file:///root/opentogethertube/server/services/hls.ts:74:42)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async HlsVideoAdapter.fetchVideoInfo (file:///root/opentogethertube/server/services/hls.ts:38:16)
[0]     at async Object.getVideoInfo (file:///root/opentogethertube/server/infoextractor.ts:172:38)
[0]     at async Object.resolveVideoQueryImpl (file:///root/opentogethertube/server/infoextractor.ts:304:21)
[0]     at async Object.resolveVideoQuery (file:///root/opentogethertube/server/infoextractor.ts:266:26)
[0]     at async addPreview (file:///root/opentogethertube/server/api/data.ts:24:24)
[0]     at async file:///root/opentogethertube/server/api/data.ts:69:9
[0] 2025-09-20 22:20:08 api/data error Unable to get add preview: TypeError: Cannot read properties of undefined (reading 'title') TypeError: Cannot read properties of undefined (reading 'title')
[0]     at HlsVideoAdapter.handleM3u8 (file:///root/opentogethertube/server/services/hls.ts:74:42)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async HlsVideoAdapter.fetchVideoInfo (file:///root/opentogethertube/server/services/hls.ts:38:16)
[0]     at async Object.getVideoInfo (file:///root/opentogethertube/server/infoextractor.ts:172:38)
[0]     at async Object.resolveVideoQueryImpl (file:///root/opentogethertube/server/infoextractor.ts:304:21)
[0]     at async Object.resolveVideoQuery (file:///root/opentogethertube/server/infoextractor.ts:266:26)
[0]     at async addPreview (file:///root/opentogethertube/server/api/data.ts:24:24)
[0]     at async file:///root/opentogethertube/server/api/data.ts:69:9
```

**Comment by Sysadminfromhell** [comment]
I have the feeling that my error is not related to yours but somewhat should also be handled correctly. I will create a seperate Issue and try to trace it down. For me in an dev env I cannot seem to get this reproduced (error 129). It always shows a correct log on the server side that the m3u8 is not complete which can and should be the case for your error too but I cannot say this for certain.

**Comment by dyc3** [comment]
TBH I'm not sure if my original reproduction is still valid anymore.
