### ISSUE TITLE
session_secret: must be of type String

### ISSUE THREAD

**Issue by Ryeera** [dyc3/opentogethertube#1531]
### Current Behavior

I set up with docker compose exactly as described in the documentation, even going as far as to trying it on another server, but both crash immediately after startup.

This is the output:
```opentogethertube           | (node:115) ExperimentalWarning: --experimental-loader may be removed in the future; instead use register():
opentogethertube           | --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
opentogethertube           | (Use node --trace-warnings ... to show where the warning was created)
opentogethertube           | (node:115) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
opentogethertube           | (node:115) ExperimentalWarning: The Node.js specifier resolution flag is experimental. It could change or be removed at any time.
opentogethertube           | (Use node --trace-warnings ... to show where the warning was created)
opentogethertube           | 2024-03-18 19:41:00 config warn No extra base config found at /app/env/docker.base.toml
opentogethertube           | 2024-03-18 19:41:00 config warn No config found at /app/env/base.toml
opentogethertube           | 2024-03-18 19:41:00 config warn No environment config found at /app/env/production.toml
opentogethertube           | /app/node_modules/convict/src/main.js:679
opentogethertube           |           throw new Error(output)
opentogethertube           |                 ^
opentogethertube           |
opentogethertube           | Error: session_secret: must be of type String
opentogethertube           |     at Object.validate (/app/node_modules/convict/src/main.js:679:17)
opentogethertube           |     at loadConfigFile (file:///app/server/ott-config.ts:496:10)
opentogethertube           |     at main (file:///app/server/app.ts:30:5)
opentogethertube           |     at file:///app/server/app.ts:213:1
opentogethertube           |     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
opentogethertube           |     at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
opentogethertube           |     at async loadESM (node:internal/process/esm_loader:34:7)
opentogethertube           |     at async handleMainPromise (node:internal/modules/run_main:106:12)
opentogethertube           |
opentogethertube           | Node.js v18.19.1
opentogethertube exited with code 1
```

Most importantly, the error seems to be that the session_secret isn't a string. So to make sure, this is my configuration (don't worry I won't be using these keys obviously):
```
hostname="localhost:8080"

log = { level="info" }

api_key="hFUoLEczm2Mj7fDmrZmSr68mwiyfY5ongVHbNMcF"
session_secret="xi5GQMaSrRNXRkhCGRpVbJh4EkY3PzWvpSEUxKpcLw93PptniPvUesM2ExGRTki484w5cprCTjLJQSaK"

[info_extractor.youtube]
api_key="[STRIPPED]" # get your own key from https://console.developers.google.com/apis/credentials
```

The api_key is 40 characters long and the session_secret is 80 characters long. But apparently, it's not a string? Am I missing something?

### Expected Behavior

I expected the docker compose stack to come up.

### Steps To Reproduce

1. Clone the Repository
2. Copy the example.toml to production.toml
3. Edit the file as described
4. Run `docker compose up`
5. See it crashing in the log over and over

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [X] I'm using the docker image.

**Comment by dyc3** [comment]
```
opentogethertube           | 2024-03-18 19:41:00 config warn No extra base config found at /app/env/docker.base.toml
opentogethertube           | 2024-03-18 19:41:00 config warn No config found at /app/env/base.toml
opentogethertube           | 2024-03-18 19:41:00 config warn No environment config found at /app/env/production.toml
```
It looks like your config is not getting loaded. The default docker-compose works for me on my machine. Have you made any modifications to the docker-compose that would prevent the volume from getting set up?

**Comment by dyc3** [comment]
Assuming this is resolved.
