### ISSUE TITLE
"SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by RandomWolf** [dyc3/opentogethertube#387]
Hi!

After first time setup and starting the server with 
NODE_ENV=production npm start

I get the folloiwing error:
```
opentube@v2202103144778147845:~/opentogethertube$ NODE_ENV=production npm start
npm WARN npm npm does not support Node.js v10.24.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> opentogethertube@0.1.0 start /home/opentube/opentogethertube
> node app.js

2021-04-04 20:34:38 app info Reading config from production.env
2021-04-04 20:34:38 app info Set log level to debug
2021-04-04 20:34:38 app info Database mode: sqlite
2021-04-04 20:34:38 app info Search enabled: true
2021-04-04 20:34:38 app info Search provider: youtube
/home/opentube/opentogethertube/server/services/dailymotion.js:8
  api = axios.create({
      ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/opentube/opentogethertube/server/infoextractor.js:3:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/opentube/opentogethertube/roommanager.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opentogethertube@0.1.0 start: `node app.js`
```

I have filled out the production.env configuration file accordingly, with a new key from the Google API.
The production.evn looks like the following:
```
OTT_HOSTNAME=localhost:8080
LOG_FILE=./logs/ott.log
LOG_LEVEL=debug
OPENTOGETHERTUBE_API_KEY=RandomStringofLettersandNumber
SESSION_SECRET=RandomStringofLettersandNumber
YOUTUBE_API_KEY=TheActualAPIKeyForTheYoutubeDataAPIv2
GOOGLE_DRIVE_API_KEY=API_KEY_GOES_HERE
DISCORD_CLIENT_ID=NONE
DISCORD_CLIENT_SECRET=NONE
GOOGLE_CLIENT_ID=NONE
GOOGLE_CLIENT_SECRET=NONE
DB_MODE=sqlite
ADD_PREVIEW_SEARCH_MIN_LENGTH=3
```
What steps doI need to take to fix this issue?

**Comment by dyc3** [comment]
You need node 12

**Comment by RandomWolf** [comment]
> You need node 12 I think. Try that.

Thank you! That fixed that particular issue, but a new one arose. Is it customary for github to open up a new issue for that, or should I continue on in this thread?

In case its the latter, the new error is: 

2021-04-04 21:45:27 app info Search provider: youtube
```
/home/opentube/opentogethertube/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:81
        throw new Error(`Please install ${moduleName} package manually`);
        ^

Error: Please install sqlite3 package manually
```

The installed sqlite3 version is 3.27.2, as checked with the "sqlite3 --version" command.

**Comment by RandomWolf** [comment]
Nervmind, npm rebuild fixed it! Thank you for your help!
