### ISSUE TITLE
out of memory on staging

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#460]
## Environment

- [ ] This happens on the official site: opentogethertube.com
- [ ] This happens using a self-hosted version.
    - [ ] I'm using the docker image.

#### Additional context

Log snippet:

```
2021-07-01T14:34:37.777454+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: ReplyError: OOM command not allowed when used memory > 'maxmemory'.

2021-07-01T14:34:37.777456+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)

2021-07-01T14:34:37.777456+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)

2021-07-01T14:34:37.777509+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4688)

2021-07-01T14:34:38.775755+00:00 app[web.1]: [32m2021-07-01 14:34:38[39m [34mroom/c9701d5736bd4f94abfcd38fb2f3bc4d[39m [1m[32mdebug[39m[22m [32msynchronizing dirty props: hasOwner,users,name,title,description,visibility,queueMode,currentSource,playbackPosition,isPlaying[39m

2021-07-01T14:34:38.777289+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: ReplyError: OOM command not allowed when used memory > 'maxmemory'.

2021-07-01T14:34:38.777291+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)

2021-07-01T14:34:38.777291+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)

2021-07-01T14:34:38.777356+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4689)

2021-07-01T14:34:39.775763+00:00 app[web.1]: [32m2021-07-01 14:34:39[39m [34mroom/c9701d5736bd4f94abfcd38fb2f3bc4d[39m [1m[32mdebug[39m[22m [32msynchronizing dirty props: hasOwner,users,name,title,description,visibility,queueMode,currentSource,playbackPosition,isPlaying[39m

2021-07-01T14:34:39.777351+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: ReplyError: OOM command not allowed when used memory > 'maxmemory'.

2021-07-01T14:34:39.777352+00:00 app[web.1]:     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)

2021-07-01T14:34:39.777352+00:00 app[web.1]:     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14)
```

**Comment by dyc3** [comment]
Closing, this doesn't seem to be a problem anymore.
