### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by mrjohnson22** [dyc3/opentogethertube#548]
### Current Behavior

When using node 12 & after following all setup instructions, `NODE_ENV=production npm start` fails as follows:

```
> opentogethertube@0.2.0 start <path>
> node app.js

2021-10-27 00:57:46 app info Reading config from production.env
2021-10-27 00:57:46 app info Set log level to info
2021-10-27 00:57:46 app info Database mode: sqlite
2021-10-27 00:57:46 app info Search enabled: true
2021-10-27 00:57:46 app info Search provider: youtube
<path>/redisclient.ts:14
    port: parseInt(process.env.REDIS_PORT ?? "", 10) || undefined,
                                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (<path>/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (<path>/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (<path>/app.js:102:25)
```

Oddly enough, installing & running this with node 16 worked okay, until some strange errors popped up at runtime (hence my attempt at switching to node 12 :slightly_smiling_face:)

### Expected Behavior

No syntax error should occur.

### Steps To Reproduce

1. Install https://github.com/tj/n/ and use it to install node 12
2. Follow the "Deployment" steps in https://github.com/dyc3/opentogethertube#readme
3. Try to run the server with `NODE_ENV=production npm start`

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
Closing as this seems to resolved.
