### ISSUE TITLE
Logged users can`t do anything after restart docker container.

### ISSUE THREAD

**Issue by SAMOXA** [dyc3/opentogethertube#637]
### Current Behavior

After restart docker container all request from users that been logged before restart fail with "usermanager error User not found" error.
```
opentogethertube    | 2022-02-20 14:37:51 usermanager error User not found
opentogethertube    | (node:108) UnhandledPromiseRejectionWarning: Error: User not found
opentogethertube    |     at Object.getUser (/usr/app/server/usermanager.js:569:10)
opentogethertube    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
opentogethertube    |     at authTokenMiddleware (/usr/app/server/auth/index.ts:42:14)
opentogethertube    | (node:108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
opentogethertube    | 2022-02-20 14:37:51 usermanager error User not found
opentogethertube    | 2022-02-20 14:37:51 clientmanager error Failed to join room: Error: User not found
opentogethertube    |     at Object.getUser (/usr/app/server/usermanager.js:569:10)
opentogethertube    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
opentogethertube    |     at RoomUser.updateInfo (/usr/app/server/room.ts:61:16)
opentogethertube    |     at Room.joinRoom (/usr/app/server/room.ts:885:3)
opentogethertube    |     at Room.processRequest (/usr/app/server/room.ts:719:4)
opentogethertube    |     at Room.processUnauthorizedRequest (/usr/app/server/room.ts:675:3)
opentogethertube    |     at Client.makeRoomRequest (/usr/app/server/clientmanager.ts:208:4)
opentogethertube    |     at Client.JoinRoom (/usr/app/server/clientmanager.ts:192:3)
opentogethertube    |     at Client.OnMessage (/usr/app/server/clientmanager.ts:111:5)
opentogethertube    | 2022-02-20 14:37:51 app info > GET /api/data/permissions
opentogethertube    | 2022-02-20 14:37:51 usermanager error User not found
opentogethertube    | (node:108) UnhandledPromiseRejectionWarning: Error: User not found
opentogethertube    |     at Object.getUser (/usr/app/server/usermanager.js:569:10)
opentogethertube    |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
opentogethertube    |     at authTokenMiddleware (/usr/app/server/auth/index.ts:42:14)
opentogethertube    | (node:108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

Workaround for this error is clear cookie and local storage on client side.

### Expected Behavior

Normal functionality after restart server.

### Steps To Reproduce

1) Startup server
2) Login User
3) Restart server
4) Try to Login/Register/Join to room in browser that used in step 2
5) Get Error in console and forever waiting on page

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [X] I'm using the docker image.

### Anything else?

Version - lattest

**Comment by dyc3** [comment]
Is your database being wiped when you restart the container? That could happen if the docker volume isn't set up correctly for the postgres container. Are you using/Have you modified the docker-compose at all?

**Comment by dyc3** [comment]
Closing because I don't really have any information to go off of.
