### ISSUE TITLE
ffprobe failed to resolve hostname

### ISSUE THREAD

**Issue by makusu720** [dyc3/opentogethertube#677]
### Current Behavior

When I try to add a mp4 video I get the error:
```An unknown error occurred when getting add preview. Try again later. ```

In the log it says:
``` opentogethertube           | 2022-06-06 10:52:12 api error Unable to get add preview: Error: Command failed: /usr/app/node_modules/@ffprobe-installer/linux-x64/ffprobe -v quiet -i "https://vjs.zencdn.net/v/oceans.mp4" -print_format json -show_streams -show_format
opentogethertube           |  Error: Command failed: /usr/app/node_modules/@ffprobe-installer/linux-x64/ffprobe -v quiet -i "https://vjs.zencdn.net/v/oceans.mp4" -print_format json -show_streams -show_format
opentogethertube           | 
opentogethertube           |     at ChildProcess.exithandler (child_process.js:383:12)
opentogethertube           |     at ChildProcess.emit (events.js:400:28)
opentogethertube           |     at ChildProcess.emit (domain.js:475:12)
opentogethertube           |     at maybeClose (internal/child_process.js:1058:16)
opentogethertube           |     at Socket.<anonymous> (internal/child_process.js:443:11)
opentogethertube           |     at Socket.emit (events.js:400:28)
opentogethertube           |     at Socket.emit (domain.js:475:12)
opentogethertube           |     at Pipe.<anonymous> (net.js:686:12)
```

When I run the command without quiet in the console I get:
```  
/usr/app/node_modules/@ffprobe-installer/linux-x64/ffprobe -i "http://vjs.zencdn.net/v/o
ceans.mp4" -print_format json -show_streams -show_format
ffprobe version N-58069-gc253b180cb-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57.  2.100 / 57.  2.100
  libavcodec     59.  3.102 / 59.  3.102
  libavformat    59.  4.101 / 59.  4.101
  libavdevice    59.  0.100 / 59.  0.100
  libavfilter     8.  0.103 /  8.  0.103
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
{
[tcp @ 0x57def00] Failed to resolve hostname vjs.zencdn.net: System error
http://vjs.zencdn.net/v/oceans.mp4: Input/output error

}
```

But I can ping the host and I get a IP:

```
ping vjs.zencdn.net
PING vjs.zencdn.net (151.101.66.217): 56 data bytes
64 bytes from 151.101.66.217: seq=0 ttl=58 time=9.176 ms
64 bytes from 151.101.66.217: seq=1 ttl=58 time=9.533 ms
64 bytes from 151.101.66.217: seq=2 ttl=58 time=13.050 ms
64 bytes from 151.101.66.217: seq=3 ttl=58 time=9.352 ms
64 bytes from 151.101.66.217: seq=4 ttl=58 time=9.443 ms
64 bytes from 151.101.66.217: seq=5 ttl=58 time=9.435 ms
^C
--- vjs.zencdn.net ping statistics ---
6 packets transmitted, 6 packets received, 0% packet loss
round-trip min/avg/max = 9.176/9.998/13.050 ms
```

### Expected Behavior

The video should be added to the queue.

### Steps To Reproduce

1. Create/Join a room
2. Try to add a direct mp4 video link

### Environment

- [ ] This happens on the official site, opentogethertube.com
- [X] This happens using a self-hosted version.
- [X] I'm using the docker image.

### Anything else?

I use Adguard Home for my DNS and i can see that the domain is resolved:
![2022-06-06_13-37](https://user-images.githubusercontent.com/36343601/172153583-f7b5c597-7524-4691-bc2c-be5832608e6c.png)

**Comment by dyc3** [comment]
try using your system's ffprobe instead. you can also change the ffprobe path using the environment variable `FFPROBE_PATH`

**Comment by makusu720** [comment]
> try using your system's ffprobe instead. you can also change the ffprobe path using the environment variable `FFPROBE_PATH`

I use UnRAID so I can only use the static build. But with this one I get:
```
/ffprobe -i "http://vjs.zencdn.net/v/oceans.mp4" -print_format json -show_streams -show_format
ffprobe version N-62022-g0dcbe1c1aa-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57. 25.100 / 57. 25.100
  libavcodec     59. 32.100 / 59. 32.100
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 39.100 /  8. 39.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
{
Segmentation fault
```

**Comment by makusu720** [comment]
I just found a note in the readme from johnvansickle. That DNS does not work in the static build.
```
A limitation of statically linking glibc is the loss of DNS resolution. Installing
nscd through your package manager will fix this.
```

**Comment by dyc3** [comment]
Huh, interesting. Unfortunately, there's not a lot else that I can do, this is a problem with ffprobe, not OTT.
