### ISSUE TITLE
Server crash on malformed websocket packet

### ISSUE THREAD

**Issue by dyc3** [dyc3/opentogethertube#784]
### Current Behavior

Server randomly crashed today, found this in the logs.

```
2022-12-01 20:39:57.384 [opentogethertube] web.1
2022-12-01 20:39:57.384 [opentogethertube] web.1 /app/node_modules/ws/lib/receiver.js:171
2022-12-01 20:39:57.384 [opentogethertube] web.1       return error(
2022-12-01 20:39:57.384 [opentogethertube] web.1              ^
2022-12-01 20:39:57.384 [opentogethertube] web.1 RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
2022-12-01 20:39:57.384 [opentogethertube] web.1     at Receiver.getInfo (/app/node_modules/ws/lib/receiver.js:171:14)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:131:22)
2022-12-01 20:39:57.384 [opentogethertube]
web.1     at Receiver._write (/app/node_modules/ws/lib/receiver.js:78:10)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at writeOrBuffer (node:internal/streams/writable:392:12)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at _write (node:internal/streams/writable:333:10)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at Receiver.Writable.write (node:internal/streams/writable:337:10)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at Socket.socketOnData (/app/node_modules/ws/lib/websocket.js:1102:35)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at Socket.emit (node:events:513:28)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at Socket.emit (node:domain:489:12)
2022-12-01 20:39:57.384 [opentogethertube] web.1     at addChunk (node:internal/streams/readable:324:12)
```

### Expected Behavior

Should disconnect client on malformed packet and not crash

### Steps To Reproduce

unknown

### Environment

- [X] This happens on the official site, opentogethertube.com
- [ ] This happens using a self-hosted version.
- [ ] I'm using the docker image.

**Comment by dyc3** [comment]
This has happened multiple times and caused a lot of downtime, so I'm going to try and find a mitigation.

Here is an excerpt from the [websocket RFC (RFC6455)](https://www.rfc-editor.org/rfc/rfc6455):

> RSV1, RSV2, RSV3:  1 bit each
>
> MUST be 0 unless an extension is negotiated that defines meanings for non-zero values.  If a nonzero value is received and none of the negotiated extensions defines the meaning of such a nonzero value, the receiving endpoint MUST _Fail the WebSocket Connection_.

**Comment by dyc3** [comment]
Figured it out: The crash occurs because if you don't implement the error handler for the socket, the default behavior is to **crash the process** for some reason.
